### ISSUE TITLE
Flatpak extension

### ISSUE THREAD

**Issue by orowith2os** [EHfive/pw-capture#1]
There are flatpak extensions for the appropriate OBS vkcapture extensions, it shouldn't be too hard to get this working too. I can look into it later.

Are there any applications that I can use to see if apps are being captured properly? I can obviously inspect the node info, but I'd rather view the windows themselves via PipeWire if possible, to be sure there isn't any artifacting and it's passing data properly.

**Comment by EHfive** [comment]
Currently there is not much GUI apps can consume pipewire video nodes directly, applications like OBS can only connect to pipewire via [xdg-desktop-portal](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.ScreenCast), which won't expose pw-capture nodes. (Though I have wrote an unpublished ad-hoc portal to test cursor capture functionality with OBS)

So Gstreamer with PipeWire provided `pipewiresrc` is the best tool to view PipeWire video nodes currently. Either or both the gstreamer inside flatpak or the gstreamer outside should work as long as it can connect to the same PipeWire server that pw-capture connects.

```bash
GST_GL_PLATFORM=egl gst-launch-1.0 pipewiresrc ! glimagesink ignore-alpha=0
# or
GST_GL_PLATFORM=egl gst-launch-1.0 pipewiresrc ! glupload ! glcolorconvert ! gldownload ! autovideosink
# try fill `target-object=` property if pipelines above don't connect
GST_GL_PLATFORM=egl gst-launch-1.0 pipewiresrc target-object=<video node's object.serial> ! glupload ! glcolorconvert ! gldownload ! autovideosink
```

Also note even if the node was registered, it could provides no format info if loaded graphic driver is missing GLX/EGL/Vulkan features/extensions required.

**Comment by EHfive** [comment]
Also this tool is far from stable and many dependencies are forked version that not published to https://crates.io . But I can tag a `0.0.1` if needed.

**Comment by orowith2os** [comment]
I'll be fine, I can just add the flatpak manifest to this repository so it can be built easily. I don't want to publish anything to Flathub (or Flathub Beta, for that matter) until everything's considered somewhat ready by both me and the upstream.
